/*
	ReflectionCodeGenerator
*/
// ReflectionCodeGenerator version 2.2.4, build 55 [Json, Binary, ImGui, EntityManager, Reflection, TypeInformation]
// File has been generated at 2021_12_19 11:41:16.603
	
#pragma once

#include "ButtonClickHandlerComponent.h"
#include "ButtonComponent.h"
#include "CameraComponent.h"
#include "DialogCloseEventHandlerComponent.h"
#include "DialogComponent.h"
#include "FeatureComponent.h"
#include "FocusComponent.h"
#include "FrameComponent.h"
#include "GuidComponent.h"
#include "HandlerTarget.h"
#include "InputTextComponent.h"
#include "LightComponent.h"
#include "MainWindowComponent.h"
#include "MathStructs.h"
#include "MenuNodeComponent.h"
#include "NameComponent.h"
#include "NeedDestroyPrefabComponent.h"
#include "NeedDestroySceneComponent.h"
#include "NeedUnloadPrefabComponent.h"
#include "NeedUnloadSceneComponent.h"
#include "ObjectInMemoryComponent.h"
#include "ParentGuidComponent.h"
#include "PositionComponent.h"
#include "PrefabGuidComponent.h"
#include "PrefabInstanceGuidComponent.h"
#include "PrefabObjectReferenceComponent.h"
#include "PrefabOriginalGuidComponent.h"
#include "PrefabReferenceComponent.h"
#include "PrefabRootComponent.h"
#include "SceneGuidComponent.h"
#include "SceneInstanceGuidComponent.h"
#include "SceneObjectReferenceComponent.h"
#include "SceneOriginalGuidComponent.h"
#include "SceneReferenceComponent.h"
#include "SceneRootComponent.h"
#include "SizeComponent.h"
#include "TitleComponent.h"
#include "TransformComponent.h"
#include "TreeNodeComponent.h"
#include "TreeViewComponent.h"
#include "VisibilityComponent.h"
#include "WindowCloseEventHandlerComponent.h"
#include "WindowComponent.h"
