/*
	ReflectionCodeGenerator
*/
// ReflectionCodeGenerator version 2.2.5, build 56 [Json, Binary, ImGui, EntityManager, Reflection, TypeInformation]
// File has been generated at 2022_01_10 22:47:23.805
	
#pragma once

#include "ButtonClickHandlerComponent.h"
#include "ButtonComponent.h"
#include "CameraComponent.h"
#include "DialogCloseEventHandlerComponent.h"
#include "DialogComponent.h"
#include "FocusComponent.h"
#include "FrameComponent.h"
#include "FrameKeyHandlerComponent.h"
#include "FrameMouseClickHandlerComponent.h"
#include "FrameMouseMoveHandlerComponent.h"
#include "FrameMouseWheelHandlerComponent.h"
#include "GuidComponent.h"
#include "HandlerTarget.h"
#include "InputTextComponent.h"
#include "InputTextValueComponent.h"
#include "LabelComponent.h"
#include "LabelValueComponent.h"
#include "LightComponent.h"
#include "MainWindowComponent.h"
#include "MathStructs.h"
#include "MenuNodeClickHandlerComponent.h"
#include "MenuNodeComponent.h"
#include "NameComponent.h"
#include "NeedDestroyObjectTagComponent.h"
#include "NodeIconComponent.h"
#include "ObjectInMemoryComponent.h"
#include "ObjectInstanceEndHandlerComponent.h"
#include "ParentGuidComponent.h"
#include "PositionComponent.h"
#include "PrefabGuidComponent.h"
#include "PrefabInstanceGuidComponent.h"
#include "PrefabObjectReferenceComponent.h"
#include "PrefabOriginalGuidComponent.h"
#include "PrefabReferenceComponent.h"
#include "PrefabRootComponent.h"
#include "SceneGuidComponent.h"
#include "SceneInstanceGuidComponent.h"
#include "SceneObjectReferenceComponent.h"
#include "SceneOriginalGuidComponent.h"
#include "SceneReferenceComponent.h"
#include "SceneRootComponent.h"
#include "SelectedTreeNodeGuidComponent.h"
#include "SizeComponent.h"
#include "SystemComponent.h"
#include "TitleComponent.h"
#include "TransformComponent.h"
#include "TreeNodeComponent.h"
#include "TreeViewComponent.h"
#include "VisibilityComponent.h"
#include "WindowCloseEventHandlerComponent.h"
#include "WindowComponent.h"
