/*
	ReflectionCodeGenerator
*/
// ReflectionCodeGenerator version 2.2.4, build 55 [Json, Binary, ImGui, EntityManager, Reflection, TypeInformation]
// File has been generated at 2021_12_13 08:08:50.285
	
#pragma once

#include "ButtonClickHandlerComponent.h"
#include "ButtonComponent.h"
#include "CameraComponent.h"
#include "DialogComponent.h"
#include "DialogVisibilityHandlerComponent.h"
#include "FeatureComponent.h"
#include "FocusComponent.h"
#include "FrameComponent.h"
#include "GuidComponent.h"
#include "HandlerTarget.h"
#include "LightComponent.h"
#include "MainWindowComponent.h"
#include "MathStructs.h"
#include "NameComponent.h"
#include "NeedDestroyPrefabComponent.h"
#include "NeedDestroySceneComponent.h"
#include "NeedUnloadPrefabComponent.h"
#include "NeedUnloadSceneComponent.h"
#include "ObjectInMemoryComponent.h"
#include "ParentGuidComponent.h"
#include "PositionComponent.h"
#include "PrefabGuidComponent.h"
#include "PrefabInstanceGuidComponent.h"
#include "PrefabObjectReferenceComponent.h"
#include "PrefabOriginalGuidComponent.h"
#include "PrefabReferenceComponent.h"
#include "PrefabRootComponent.h"
#include "SceneGuidComponent.h"
#include "SceneInstanceGuidComponent.h"
#include "SceneObjectReferenceComponent.h"
#include "SceneOriginalGuidComponent.h"
#include "SceneReferenceComponent.h"
#include "SceneRootComponent.h"
#include "SizeComponent.h"
#include "TitleComponent.h"
#include "TransformComponent.h"
#include "VisibilityComponent.h"
#include "WindowComponent.h"
#include "WindowVisibilityHandlerComponent.h"
