/*
test
*/
// File has been generated by ReflectionCodeGenerator version 1.12 build 40, at 2020_08_14 14:07:03.576
	
#pragma once

#include "BaseStruct.h"
#include "TestClass.h"
#include "TestStruct.h"
