/*
test
*/
// File has been generated by ReflectionCodeGenerator version 1.15 build 43, at 2020_09_25 20:04:35.320
	
#pragma once

#include "BaseStruct.h"
#include "TestClass.h"
#include "TestStruct.h"
