/*
Author: Gudakov Ramil Sergeevich a.k.a.Gauss
Гудаков Рамиль Сергеевич
Contacts : [ramil2085@mail.ru, ramil2085@gmail.com]
See for more information License.h.
*/
// File has been generated by ReflectionCodeGenerator version 0.50 build 12, at 2019_01_21 13:55:08.940
	
#pragma once

#include <string>
#include "JsonMaster.h"
#include "json11.h"
#include "IncludeList.h"

namespace nsJson
{
  class  TJsonSerializer
  {
    typedef TJsonMaster::Jobj Jobj;
  public:
    template <typename Type>
    static void Serialize( Type* p, std::string& str );
  
    template <typename Type>
    static void Deserialize( Type*& p, std::string& str );
  
    template <typename Type>
    static void Fill( Type* p, std::string& str );
  private:
    template <typename Type>
    static void _Deserialize( Type*& p, std::string& str, bool checkPtr );
  private:
    static void _Serialize( TBaseStruct* p, Jobj& obj );
    static void _Deserialize( TBaseStruct* p, const json11::Json& json );
    
    static void _Serialize( TTestClass* p, Jobj& obj );
    static void _Deserialize( TTestClass* p, const json11::Json& json );
    
    static void _Serialize( TTestStruct* p, Jobj& obj );
    static void _Deserialize( TTestStruct* p, const json11::Json& json );
    
  };
  //------------------------------------------------------------------------------------
  template <typename Type>
  void TJsonSerializer::Serialize( Type* p, std::string& str )
  {
    Jobj obj;
    _Serialize( p, obj );
    json11::Json json( obj );
    str = json.dump();
  }
  //------------------------------------------------------------------------------------
  template <typename Type>
  void TJsonSerializer::Deserialize( Type*& p, std::string& str )
  {
    _Deserialize( p, str, true );
  }
  //------------------------------------------------------------------------------------
  template <typename Type>
  void TJsonSerializer::Fill( Type* p, std::string& str )
  {
    _Deserialize( p, str, false );
  }
  //------------------------------------------------------------------------------------
  template <typename Type>
  void TJsonSerializer::_Deserialize( Type*& p, std::string& str, bool checkPtr )
  {
    std::string err;
    auto json = json11::Json::parse( str, err, json11::JsonParse::COMMENTS );
    if ( err.size() > 0 )
      return;
  
    if ( checkPtr )
      p = p ? p : new Type();
  
    _Deserialize( p, json.object_items() );
  }
  //------------------------------------------------------------------------------------
}
