/*
Author: Gudakov Ramil Sergeevich a.k.a.Gauss
Гудаков Рамиль Сергеевич
Contacts : [ramil2085@mail.ru, ramil2085@gmail.com]
See for more information LICENSE.md.
*/
// File has been generated by ReflectionCodeGenerator version 1.9 build 38, at 2020_05_15 15:43:07.935
	
#include "GameEngineJsonSerializer.h"
#include "fmt/core.h"
#include "JsonPopMaster.h"
#include "JsonPushMaster.h"


using POM = TJsonPopMaster;
using PUM = TJsonPushMaster;

void TGameEngineJsonSerializer::_Serialize( TAppConfig* p, Jobj& obj )
{
  
  Jarr modules_c0;
  for ( auto& modules_e0 : p->modules )
  {
    modules_c0.push_back( modules_e0 );
  }
  PUM::Push( obj, "modules", modules_c0 );
}
//---------------------------------------------------------------------------------------
void TGameEngineJsonSerializer::_Deserialize( TAppConfig* p, const json11::Json& json )
{
  
  auto& modules_src0 = json["modules"].array_items();
  for ( auto& modules_e0 : modules_src0 )
  {
    p->modules.push_back( modules_e0.string_value() );
  }
}
//---------------------------------------------------------------------------------------
void TGameEngineJsonSerializer::_Serialize( TConveyerConfig* p, Jobj& obj )
{
  
  Jobj appList_c0;
  for ( auto& appList_e0 : p->appList )
  {
    Jobj appList_e0_obj;
    auto& appList_e0_value = appList_e0.second;
    auto appList_e0_ptr = &appList_e0_value;
    if ( appList_e0_ptr )
    {
      _Serialize( appList_e0_ptr, appList_e0_obj );
      appList_c0.insert( { fmt::format( "{}", appList_e0.first ), appList_e0_obj } );
    }
    else
      appList_c0.insert( { fmt::format( "{}", appList_e0.first ), nullptr } );
  }
  PUM::PushMap( obj, "appList", appList_c0 );
}
//---------------------------------------------------------------------------------------
void TGameEngineJsonSerializer::_Deserialize( TConveyerConfig* p, const json11::Json& json )
{
  
  auto& appList_src0 = json["appList"].object_items();
  for ( auto& appList_e0 : appList_src0 )
  {
    auto& first_e0 = appList_e0.first;
    auto& second_e0 = appList_e0.second;
    TAppConfig appList_newObj0;
    if ( second_e0.is_null() == false )
    {
      _Deserialize( &appList_newObj0, second_e0 );
    }
    p->appList.insert( { appList_e0.first, appList_newObj0 } );
  }
}
//---------------------------------------------------------------------------------------
