/*
Author: Gudakov Ramil Sergeevich a.k.a.Gauss
Гудаков Рамиль Сергеевич
Contacts : [ramil2085@mail.ru, ramil2085@gmail.com]
See for more information License.h.
*/
// File has been generated by ReflectionCodeGenerator version 1.7 build 36, at 2019_02_08 17:21:11.369
	
#include "JsonSerializer.h"
#include "fmt/core.h"
#include "JsonPopMaster.h"
#include "JsonPushMaster.h"

using namespace nsGameEngine;

using POM = TJsonPopMaster;
using PUM = TJsonPushMaster;

void TJsonSerializer::_Serialize( TAppConfig* p, Jobj& obj )
{
  
  Jarr modulesInThreads_c0;
  for ( auto& modulesInThreads_e0 : p->modulesInThreads )
  {
    Jarr modulesInThreads_c1;
    for ( auto& modulesInThreads_e1 : modulesInThreads_e0 )
    {
      modulesInThreads_c1.push_back( modulesInThreads_e1 );
    }
    modulesInThreads_c0.push_back( modulesInThreads_c1 );
  }
  PUM::Push( obj, "modulesInThreads", modulesInThreads_c0 );
}
//---------------------------------------------------------------------------------------
void TJsonSerializer::_Deserialize( TAppConfig* p, const json11::Json& json )
{
  
  auto& modulesInThreads_src0 = json["modulesInThreads"].array_items();
  for ( auto& modulesInThreads_e0 : modulesInThreads_src0 )
  {
    std::vector<std::string> modulesInThreads_c1;
    auto& modulesInThreads_src1 = modulesInThreads_e0.array_items();
    for ( auto& modulesInThreads_e1 : modulesInThreads_src1 )
    {
      modulesInThreads_c1.push_back( modulesInThreads_e1.string_value() );
    }
    p->modulesInThreads.push_back( modulesInThreads_c1 );
  }
}
//---------------------------------------------------------------------------------------
void TJsonSerializer::_Serialize( TConveyerConfig* p, Jobj& obj )
{
  
  Jobj appList_c0;
  for ( auto& appList_e0 : p->appList )
  {
    Jobj appList_e0_obj;
    auto& appList_e0_value = appList_e0.second;
    auto appList_e0_ptr = &appList_e0_value;
    if ( appList_e0_ptr )
    {
      _Serialize( appList_e0_ptr, appList_e0_obj );
      appList_c0.insert( { fmt::format( "{}", appList_e0.first ), appList_e0_obj } );
    }
    else
      appList_c0.insert( { fmt::format( "{}", appList_e0.first ), nullptr } );
  }
  PUM::PushMap( obj, "appList", appList_c0 );
}
//---------------------------------------------------------------------------------------
void TJsonSerializer::_Deserialize( TConveyerConfig* p, const json11::Json& json )
{
  
  auto& appList_src0 = json["appList"].object_items();
  for ( auto& appList_e0 : appList_src0 )
  {
    auto& first_e0 = appList_e0.first;
    auto& second_e0 = appList_e0.second;
    TAppConfig appList_newObj0;
    if ( second_e0.is_null() == false )
    {
      _Deserialize( &appList_newObj0, second_e0 );
    }
    p->appList.insert( { appList_e0.first, appList_newObj0 } );
  }
}
//---------------------------------------------------------------------------------------
