/*
	ReflectionCodeGenerator
*/
// File has been generated by ReflectionCodeGenerator version 1.18 build 46, at 2020_10_02 12:49:13.352
	
#pragma once

#include "FrameworkResources.h"
#include "MathStructs.h"
