/*
Author: Gudakov Ramil Sergeevich a.k.a.Gauss
Гудаков Рамиль Сергеевич
Contacts : [ramil2085@mail.ru, ramil2085@gmail.com]
See for more information License.h.
*/
// File has been generated by ReflectionCodeGenerator version 1.7 build 36, at 2019_02_08 10:05:43.141
	
#pragma once

#include "BaseStruct.h"
#include "ParamClass.h"
#include "TestClass.h"
#include "TestStruct.h"
