/*
	ReflectionCodeGenerator for Marshaller
*/
// File has been generated by ReflectionCodeGenerator version 1.18 build 46, at 2020_10_02 11:57:23.798
	
#pragma once

#include "BaseStruct.h"
#include "ParamClass.h"
#include "TestClass.h"
#include "TestStruct.h"
