/*
Author: Gudakov Ramil Sergeevich a.k.a.Gauss
Гудаков Рамиль Сергеевич
Contacts : [ramil2085@mail.ru, ramil2085@gmail.com]
See for more information License.h.
*/
// File has been generated by ReflectionCodeGenerator version 1.6 build 34, at 2019_02_06 14:57:34.813
	
#pragma once

#include "BaseStruct.h"
#include "ParamClass.h"
#include "TestClass.h"
#include "TestStruct.h"
