/*
	ReflectionCodeGenerator for Marshaller
*/
// File has been generated by ReflectionCodeGenerator version 1.18 build 46, at 2020_10_02 11:57:23.845
	
#pragma once

#include <string>
#include <map>
#include <functional>
#include "IncludeList.h"

namespace nsReflection
{
    class TReflection
    {
    public:
        static void* New(const std::string& typeName);
    private:
        struct Data
        {
            std::string typeName;
            std::function<void* ()> newFunc;
        };
    
        static std::map<std::string, Data> mTypeNameMap;
    
        static void Init();
    };
}
