/*
Author: Gudakov Ramil Sergeevich a.k.a. Gauss
Гудаков Рамиль Сергеевич
Contacts: [ramil2085@mail.ru, ramil2085@gmail.com]
See for more information License.h.
*/

#pragma once

#include "IGenerator.h"

namespace nsReflectionCodeGenerator
{
  class IFileGenerator : public IGenerator
  {
  protected:
    const std::list<std::string> s_Header =
    { 
      "/*",
      "Author: Gudakov Ramil Sergeevich a.k.a.Gauss",
      "Гудаков Рамиль Сергеевич",
      "Contacts : [ramil2085@mail.ru, ramil2085@gmail.com]",
      "See for more information License.h.",
      "*/" 
    };

    const std::string s_TimeHeader = "// File has been generated by {} version {} build {}, at {}";

    TStrListPair* pStrListPair = nullptr;
  public:
    void Init( TStrListPair& strListPair );

    virtual void Work() = 0;

  protected:
    void AddHeader();
    void AddTimeHeader();

    void AddEmptyLine();

    void AddPragmaOnce();

    void AddInclude( const std::string& fileName );
  protected:
    void Add( const std::string& str );
  };
}
