/*
Author: Gudakov Ramil Sergeevich a.k.a. Gauss
Гудаков Рамиль Сергеевич
Contacts: [ramil2085@mail.ru, ramil2085@gmail.com]
See for more information License.h.
*/

#pragma once

#include "IGenerator.h"

namespace nsReflectionCodeGenerator
{
  class IFileGenerator : public IGenerator
  {
  protected:
    const std::list<std::string> s_Header =
    {
      "/*",
      "Author: Gudakov Ramil Sergeevich a.k.a.Gauss",
      "Гудаков Рамиль Сергеевич",
      "Contacts : [ramil2085@mail.ru, ramil2085@gmail.com]",
      "See for more information License.h.",
      "*/"
    };

    const std::string s_TimeHeader = "// File has been generated by {} version {} build {}, at {}";

    const std::string sTab = "  ";

    TStrListPair* pStrListPair = nullptr;

  private:
    int mTabCounter = 0;
  public:
    void Init( TStrListPair& strListPair );

    virtual void Work() = 0;

  protected:
    void AddHeader();
    void AddTimeHeader();

    void AddEmptyLine();

    void AddPragmaOnce();

    void AddInclude( const std::string& fileName );
    void AddStandartInclude( const std::string& fileName );
    void AddNamespaceBegin( const std::string& namespaceName );
    void AddNamespaceEnd();

    void AddClassBegin( const std::string& exportDeclaration, const std::string& className );
    void AddClassEnd();

    void AddPublicSection();
    void AddProtectedSection();
    void AddPrivateSection();

    void IncrementTabs();
    void DecrementTabs();
    void ClearTabs();

  protected:
    void Add( const std::string& str );
    void AddIncludeExt( const std::string& fileName, const std::string& beginBrace, const std::string& endBrace );

    std::string AddTabsToStr( const std::string& str, int tabCounter );
  };
}
