/*
Author: Gudakov Ramil Sergeevich a.k.a.Gauss
Гудаков Рамиль Сергеевич
Contacts : [ramil2085@mail.ru, ramil2085@gmail.com]
See for more information LICENSE.md.
*/
// File has been generated by ReflectionCodeGenerator version 1.9 build 38, at 2020_05_15 15:46:49.594
	
#pragma once

#include "BaseStruct.h"
#include "Config.h"
#include "ParamClass.h"
#include "TestClass.h"
#include "TestStruct.h"
