set PATH=%PATH%;%DEP_PATH_MMO_FRAMEWORK%\Bin;%DEP_PATH_MMO_FRAMEWORK%\Bin\ssl32;%DEP_PATH_MMO_FRAMEWORK%\Bin\ssl64;%DEP_PATH_MMO_FRAMEWORK%\Include\ODB\odb-2.4.0-i686-windows\bin;%POSTGRESQL_DEV%\bin

start MMOFramework.sln